CREATE TABLE IF NOT EXISTS /*_*/edusharing_resource (
EDUSHARING_RESOURCE_ID bigint(10) unsigned NOT NULL PRIMARY KEY auto_increment,
EDUSHARING_RESOURCE_PAGE_ID bigint(10) unsigned NOT NULL,
EDUSHARING_RESOURCE_USAGE varchar(255) NULL,
EDUSHARING_RESOURCE_TITLE varchar(255) NOT NULL,
EDUSHARING_RESOURCE_OBJECT_URL varchar(255) NOT NULL	,
EDUSHARING_RESOURCE_OBJECT_VERSION varchar(32) NOT NULL DEFAULT 1.0,
EDUSHARING_RESOURCE_WIDTH int(9) unsigned NULL,
EDUSHARING_RESOURCE_HEIGHT int(9) unsigned NULL,
EDUSHARING_RESOURCE_FLOAT varchar(32) NOT NULL DEFAULT 'none',
INDEX id_usage (EDUSHARING_RESOURCE_USAGE)
)/*$wgDBTableOptions*/;
